// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.recover.protos;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.recover.protos.Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string databaseName = 1;</code>
   * @return Whether the databaseName field is set.
   */
  boolean hasDatabaseName();
  /**
   * <code>optional string databaseName = 1;</code>
   * @return The databaseName.
   */
  java.lang.String getDatabaseName();
  /**
   * <code>optional string databaseName = 1;</code>
   * @return The bytes for databaseName.
   */
  com.google.protobuf.ByteString
      getDatabaseNameBytes();

  /**
   * <code>optional string path = 2;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <code>optional string path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional string context = 3;</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>optional string context = 3;</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>optional string context = 3;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();
}
