// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.recover.protos;

public final class NodeProtos {
  private NodeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_recover_protos_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_recover_protos_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_recover_protos_NodeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_recover_protos_NodeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_recover_protos_NodeMessage_MessageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_recover_protos_NodeMessage_MessageEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\022com.recover.protos\"p\n\004Node" +
      "\022\031\n\014databaseName\030\001 \001(\tH\000\210\001\001\022\021\n\004path\030\002 \001(" +
      "\tH\001\210\001\001\022\024\n\007context\030\003 \001(\tH\002\210\001\001B\017\n\r_databas" +
      "eNameB\007\n\005_pathB\n\n\010_context\"\226\001\n\013NodeMessa" +
      "ge\022=\n\007message\030\001 \003(\0132,.com.recover.protos" +
      ".NodeMessage.MessageEntry\032H\n\014MessageEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\'\n\005value\030\002 \001(\0132\030.com.reco" +
      "ver.protos.Node:\0028\001B\"\n\022com.recover.proto" +
      "sB\nNodeProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_recover_protos_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_recover_protos_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_recover_protos_Node_descriptor,
        new java.lang.String[] { "DatabaseName", "Path", "Context", "DatabaseName", "Path", "Context", });
    internal_static_com_recover_protos_NodeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_recover_protos_NodeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_recover_protos_NodeMessage_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_recover_protos_NodeMessage_MessageEntry_descriptor =
      internal_static_com_recover_protos_NodeMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_recover_protos_NodeMessage_MessageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_recover_protos_NodeMessage_MessageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
